main: me.miunapa.money.Main
name: PAMoney
author: MiunaPA
version: 1.0.4
depend: [Vault]
api-version: 1.15

commands:
  money:
    description: 回到上一個傳送點
    usage: /money
    permission: pamoney.user

permissions:
  pamoney.*:
    description: 關於PA-Money的所有權限
    childred:
      pamoney.op: true
      pamoney.user: true
      pamoney.admin: true

  pamoney.op:
    description: 大管理員能用的指令
    children:
      pamoney.grant: true
      pamoney.deduct: true
      pamoney.set: true
  pamoney.admin:
    description: 小管理員能用的指令
    children:
      pamoney.lookup.other: true
  pamoney.user:
    description: 玩家能用的指令
    children:
      pamoney.lookup: true
      pamoney.help: true
      pamoney.pay: true
      pamoney.top: true

  pamoney.grant:
    description: 增加餘額
    default: op
  pamoney.deduct:
    description: 減少餘額
    default: op
  pamoney.set:
    description: 設定餘額
    default: op

  pamoney.help:
    description: 幫助
    default: true
  pamoney.pay:
    description: 給別人錢
    default: true
  pamoney.top:
    description: 查看排行榜
    default: true
  
  pamoney.lookup:
    description: 查看金錢交易紀錄
    default: true  
  pamoney.lookup.other:
    description: 查看金錢交易紀錄(別人)
    default: op  